name = "api-dromzeh-dev"
main = './src/index.ts'
compatibility_date = "2024-04-19"

account_id = "ba4e8f7f9ffbc23dba6acd0d9bd3ef46"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "bucket"
bucket_name = "cdn-dromzeh-dev"
preview_bucket_name = "cdn-dromzeh-dev"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"